version: '3.7'
services:
  db:
    image: postgres:17
    container_name: OnlineShop_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
  
  redis:
    image: redis:7
    container_name: OnlineShop_redis
  
  OnlineShop:
    image: onlineshop_image
    build:
      context: . 
    container_name: OnlineShop_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis 
    command: alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    ports:
      - 7777:8000
  
  celery:
    build:
      context: . 
    container_name: OnlineShop_celery    
    command: sh -c "celery --app=app.infrastructure.tasks.celery_app:celery worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis 

  flower:
    build:
      context: . 
    container_name: OnlineShop_flower
    command: sh -c "celery --app=app.infrastructure.tasks.celery_app:celery flower"
    env_file:
      - .env-non-dev
    depends_on:
      - redis 