"""empty message

Revision ID: 8e1139e546e3
Revises: 606d79b696b8
Create Date: 2024-10-24 20:58:25.815922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1139e546e3'
down_revision: Union[str, None] = '606d79b696b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('shipped', 'delivered', 'pending', name='status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('shipped', 'delivered', 'pending', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
